### PR TITLE
Add 868 MHz versions of Flipper RF commands

### PR DESCRIPTION
**Pull request by sean1983**
Updated, RF Commands
 * Added Sub-Folder for 868 Mhz
 * Added modified all .sub files changing Frequency from 915 Mhz to 868 Mhz.

Updated, README's
 * Updated RF General README for 868 Mhz changes.
 * Updated 'Edited RF Commands' README for 868 Mhz changes.

### CODE REVIEW

**Comment by danielweidman** [comment]
Excellent, thank you for figuring out the European frequency, confirming the same commands work, and adding these files!

**Comment by andoma93** [comment]
Hello @danielweidman , @sean1983 
I cannot understand how to make them work with Flipper zero.

I have an European one but it doesn't work

**Comment by sean1983** [comment]
> work

Hi Mate,  

First off,  What event was this from ?

I would suggest first to check the batteries are good,  These RF Models drain batteries fast.

**Comment by andoma93** [comment]
Hello @sean1983,
thanks for your reply.

It was from Coldplay event in Milan on July 4th 2017.

- Bracelet is Xyloband
- Batteries were drained and has been substituted. Now when it starts just blink once so it seems ok

Thanks you

**Comment by sean1983** [comment]
Hi @andoma93 

Arhh!

Well, there is your problem!  Xylobands are completely different.

Same Frequencies but completely different modulation type and encoding.

At the moment, we are currently only working with Pixmob Bracelets that Coldplay use these days! Which are Infrared but recently Pixmob have started using RF too!

There is github project for controlling Xylobands out there,  But not for the Flipper Zero as of yet.

But saying that,  I have recently Posted a couple of Xyloband over to Dani the Author of this project.   And once he has some time to play around with them we might end up with some control of them some point in the future!

**Pull request merged**
